### ISSUE TITLE
Grant type password requires client_secret

### ISSUE THREAD

**Issue by krmarien** [lepture/flask-oauthlib#246]
When trying to authenticate using the grant_type "password" the client_secret is required even if the client is not confidential

I have this issue in version 0.9.2, previously in version 0.9.1 the client_secret was not needed.

Is it possible the `client_authentication_required` was wrongly changed?

**Comment by LordSputnik** [comment]
This was broken in d66849276d37552cdd02473924de875a794edca6 - we just upgraded to 0.9.2 and had to spend a few hours tracking this down. From what I've read, the new behaviour doesn't follow RFC6749.

**Comment by lepture** [comment]
Just reverted https://github.com/lepture/flask-oauthlib/commit/8d4faabf17f2fa99ab5f927d3f94fbb1641ab914

Could anyone help me write test cases: `tests/test_oauth2`?

**Comment by nicolaiarocci** [comment]
Hi, looks like this regression is still going on. See https://github.com/nicolaiarocci/flask-sentinel/issues/9.

**Comment by lepture** [comment]
@nicolaiarocci Is the master works fine?

**Comment by nicolaiarocci** [comment]
@lepture nope it still crashes on [this line](https://github.com/lepture/flask-oauthlib/commit/27aa740ff3994e18825c2ed949ce5196ef5be3f8#diff-caa6a21372b10b235c8cf7e00402330bR596) with

    AttributeError: 'Client' object has no attribute 'client_secret'

**Comment by lepture** [comment]
@nicolaiarocci sorry for this. I've just updated.

**Comment by nicolaiarocci** [comment]
It's fine now! Thanks for the super-fast response  👍
